version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    command: ./scripts/entrypoint.django.sh
    env_file: .env.local
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: pretask
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
