# Generated by Django 3.2.20 on 2024-07-28 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Contact number must only contain digits and '-'.", regex='^[0-9-]+$')])),
                ('company', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('labels', models.ManyToManyField(blank=True, related_name='contacts', to='contact.Label')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
